geometry_msgs/Point IMUorientation
geometry_msgs/Point IMUgyro
geometry_msgs/Point COMLSSP
geometry_msgs/Point COMRSSP
geometry_msgs/Point COMDSP
geometry_msgs/Point COMLSSPrpy
geometry_msgs/Point COMRSSPrpy
geometry_msgs/Point COMDSPrpy
geometry_msgs/Point ZMPLSSP
geometry_msgs/Point ZMPRSSP
geometry_msgs/Point ZMPDSP

#geometry_msgs/Transform LAnklePitch
#geometry_msgs/Transform RAnklePitch

float32 LAnklePitch_velocityNow  
float32 LAnklePitch_positionIK   
float32 LAnklePitch_positionNow  
float32 LAnklePitch_refPosFromPos 
float32 RAnklePitch_velocityNow  
float32 RAnklePitch_positionIK   
float32 RAnklePitch_positionNow 
float32 RAnklePitch_refPosFromPos

float32 COMDSPrpy_pitch_Est
float32 gyro_pitch_Est
float32 COMDSPrpy_pitch_Meas
float32 gyro_pitch_Meas
float32 gyro_pitch_Fil

float32 CP_0
float32 CP_1
float32 CP_2
float32 CP_3