GET http://127.0.0.1:5000/init?robot=Abi

# POST http://127.0.0.1:5000/init/Abi
Content-Type: application/json

{
    "robot": "Abi",
    "data": {
       "r_sho_roll": 1.0,
       "r_sho_pitch": 2.0,
       "r_el_pitch": 3.0,
       "r_hip_roll": 0.0,
       "r_hip_pitch": 0.0,
       "r_hip_yaw": 0.0,
       "r_knee_pitch": 0.0,
       "r_ank_roll": 0.0,
       "r_ank_pitch": 0.0,
       "head_tilt": 0.0,
       "head_pan": 0.0,
       "l_sho_roll": 0.0,
       "l_sho_pitch": 0.0,
       "l_el_pitch": 0.0,
       "l_hip_roll": 0.0,
       "l_hip_pitch": 0.0,
       "l_hip_yaw": 0.0,
       "l_knee_pitch": 0.0,
       "l_ank_roll": 0.0,
       "l_ank_pitch": 0.0
    }
}