kicking:
  ballPosX: 0.29999999999999999
  Gain_Angle_Pitch: 0
  L_Shift: 0.0399999991
  Time_CoolDown: 0.449999988
  Time_Retract: 0.400000006
  Time_Kick: 0.100000001
  Body_Height: 0.354999989
  Gain_Velocity_Roll: 0
  Time_Shift: 1
  Leg_Z: 0
  Gain_Angle_Roll: 0.5
  X_Retract: 0.0799999982
  Leg_Y: 0.0649999976
  ballPosZ: 0.089999999999999997
  R_Roll: 0.600000024
  Leg_X: 0
  R_CoolDown: 0
  Leg_R_X: 0
  Time_BringDown: 0.300000012
  Gain_Velocity_Pitch: 0
  Gain_Integral: 0
  Time_Lift: 0.200000003
  L_Lift: 0
  R_Lift: -0.0299999993
  Z_Retract: 0.119999997
  Leg_L_X: 0
  Body_Tilt: 12
  L_Roll: -0.620000005
  R_Shift: -0.0450000018
  L_CoolDown: 0
button_setting:
  L3: 3
  L1: 1
  R1: 5
  R4: 8
  L2: 2
  R2: 6
  L4: 4
  R3: 7
main_program:
  WalkingReady: 86
  GetUpBack: 192
  KeeperRight: 33
  LeftKick: 34
  GetUpLeft: 195
  GetUpRight: 194
  KeeperFront: 35
  KeeperLeft: 34
  KeeperReady: 7
  Ceremony: 27
  RightKick: 33
  GetUpFront: 191
  InitPose: 1
feedback:
  Gain_Integral_Roll: 0
  Gain_Velocity_Roll: 0
  Leg_L_Z: -0.01
  Body_Tilt: 10
  L_Roll: 15
  R_Roll: -15
  Gain_Angle_Pitch: 0
  Setpoint_Roll: -0.075
  Setpoint_Pitch: 0
  Leg_X: -0.01
  Leg_R_Z: -0.01
  Gain_Integral_Pitch: 0
  Body_Height: 0.34
  Leg_Y: 0.065
  Leg_Z: 0
  Gain_Velocity_Pitch: 0
  Gain_Angle_Roll: 0.5
kicking_v10:
  LANDING_TIME: 0.22
  Lift_Pitch: 0
  R_Swing_X: 0.25
  L_Retract_Z: 0.118
  L_Swing_Y: 0.03
  R_Shift_Y: 0.08
  SWING_TIME: 0.12
  Retract_Pitch: 3
  L_Shift_Z: 0.35
  FINISHED_TIME: 0.2
  R_Retract_Z: 0.115
  SHIFT_TIME: 1.7
  R_Swing_Z: 0.08
  R_Retract_X: 0
  Retract_Roll: 15
  R_Retract_Y: -0.1
  Lift_Roll: 24
  Swing_Roll: 15
  Torso_Z: 0.356
  R_Lift_Z: 0.1
  L_Retract_Y: 0.10
  Torso_X: 0.007
  R_Swing_Y: -0.07
  R_Lift_Y: -0.055
  L_Lift_Z: 0.23
  R_Lift_X: -0.12
  L_Shift_X: 0.008
  Swing_Pitch: 25
  LIFT_TIME: 0.42
  L_Lift_X: -0.25
  L_Retract_X: -0.008
  RETRACT_TIME: 0.2
  L_Swing_Z: 0.128
  Torso_Pitch: 10
  Shift_Roll: 17
  L_Swing_X: 0.45
  L_Shift_Y: -0.061
  Torso_Y: 0
  R_Shift_X: 0
  L_Lift_Y: 0.028
  R_Shift_Z: 0.355
general:
  U2D2: /dev/ttyUSB0
  robot_name: alfa
  useComm: true
  role: Striker
  baudrate: 1000000
  robot_id: 1
  team_id: 6
mcl_localization:
  vgauss_y: 1
  mcl_afast: 0.1
  mcl_wcmps: 0.01
  variance: 0.03
  mgauss_x: 4
  mgauss_y: 4
  mcl_aslow: 0.01
  mgauss_w: 2
  vgauss_x: 1
walk_zmp:
  supportFront: 0.0199999996
  kneeX_fact: 0
  bodyTilt: 8.0214091659824707
  armY_deadband: 0
  vx_manip: 0
  ArmRoll: 15
  L_Lift: 0
  supportX: 0
  tZmp: 0.18616797
  TH1: 0.00600000005
  default_imu_y: -30
  armX_deadband: 0
  GainVelocityPitch: 0.0199999996
  supportFront2: 0.0500000007
  TH2: 0.0500000007
  R_P_Cool: 0
  velfast_turn: 0.150000006
  hipY_fact: 0
  footY: 0.0549999997
  ArmElbow: 0
  vy_manip: 0
  ankleX_maxVal: 0
  ankleX_deadband: 0
  armY_maxVal: 0
  bodyHeight: 0.340000004
  kneeX_maxVal: 0
  frontComp: 0
  L_Shift: 0
  supportTurn: 0.100000001
  Kd: 0
  kneeX_deadband: 0
  Acc: 0.109999999
  GainVelocityRoll: 0.0199999996
  supportSideX: 0
  GainAngleRoll: 0.800000012
  ArmPitch: 90
  ankleY_deadband: 0
  Kp: 0
  supportSideY: 0.0399999991
  ankleY_fact: 0
  ankleX_fact: 0
  R_P_Kick: 0
  armY_fact: 0
  GainIntegral: 0
  L_P_Cool: 0
  tStep: 0.319999993
  vphi_manip: 0
  stepHeight: 0.0549999997
  supportY: 0.0399999991
  L_P_Kick: 0
  armX_maxVal: 0
  hipY_deadband: 0
  footX: 0
  R_Lift: 0
  GainAnglePitch: 1
  hipY_maxVal: 0
  armX_fact: 0
  ankleY_maxVal: 0
  velfast_forward: 0.0299999993
  R_Shift: 0
kick_params:
  TRetract: 0.3
  R_Tilt: 13
  ballPosX: 0.060
  ballPosZ: 0.100
  power: 0.250
  TRising: 0.5
  goalPosX: 0.100
  ballPosY: 0.000
  TKick: 0.2
  TDown: 0.1
  goalPosY: 0.000
  L_Tilt: 8
  goalPosZ: 0.100
arduino_controller:
  offset: 0.0