feedbackMode: 1
KrZMPX: 2
KrZMPY: 66.65
RightKickZMPrefY: 0.005
RightKickZMPrefX: 0.03
LeftKickZMPrefY: -0.005
LeftKickZMPrefX: 0.03
DSPZMPrefY: 0
DSPZMPrefX: -0.005
KiZMPY: 0
KiZMPX: 0
KAngleRoll: 0
KGyroRoll: 0
KAnglePitch: 0.34
KGyroPitch: 0.001
KCOMX: -0.8
KZMPX: 0.0
angleErrorMAX: 8
angleErrorMIN: -18
highGainMAX: 3.2
highGainMIN: 2
