Gain_Angle_Pitch: 1
Gain_Angle_Roll: 0
Gain_Integral_Angle_Pitch: 0
Gain_Integral_Angle_Roll: 0
Gain_Velocity_Pitch: 0.0500000007
Gain_Velocity_Roll: 0
Gain_Hip_Roll: 0
Gain_Hip_Pitch: 0.200000003
Gain_Knee: 0
Gain_Ankle_Pitch: 0.300000012
Gain_Ankle_Roll: 0
Gain_Shoulder_Pitch: 0
setpointPitch: 0
pitch_error_tol: 30
GainKPX: 0
GainKDX: 0
GainKIX: 0
setpointX: 0.0599999987
x_error_tol: 0.00300000003