footPutDownPhase: 1
trunkPitchPCoefForward: 0
footDistance: 0.13
trunkXOffset: 0.03
trunkHeight: 0.38
footRise: 0.05
trunkYOffset: -0.003
trunkPause: 0.5
footOvershootRatio: 0.05
trunkPitchPCoefTurn: 0
trunkPhase: 0.5
freq: 1.6
trunkSwing: 0.2
trunkPitch: 0.2792527
footApexPhase: 0.5
footPutDownZOffset: 0
doubleSupportRatio: 0.05
trunkXOffsetPCoefTurn: 0
footOvershootPhase: 0.85
trunkYOnlyInDoubleSupport: false
trunkXOffsetPCoefForward: 0.3