Gyro_3: 40
footOvershootRatio: 0.05
trunkPhase: 0.6
trunkPitch: 0.2443461
footPutDownZOffset: 0
trunkPitchPCoefTurn: 0
Angle_0: 9
Angle_4: 10
trunkPause: 0.5
KP_3: 0.1
footPutDownPhase: 1
Angle_2: 3
KP_1: 0.2
Gyro_0: 80
KD_0: 0.23
KP_0: 0.3
trunkXOffsetPCoefTurn: 0
trunkHeight: 0.38
trunkXOffset: -0.015
KP_4: 0.3
trunkPitchPCoefForward: 0
trunkYOffset: -0.005
trunkSwing: 0.22
footOvershootPhase: 0.85
KD_3: 0.19
Angle_3: 8
footRise: 0.05
freq: 1.65
Gyro_4: 80
KD_P_qw: 0
Angle_1: 7
KD_1: 0.18
Gyro_2: 0
Gyro_1: 40
doubleSupportRatio: 0.045
setpointPitch: 1
KP_2: 0
trunkXOffsetPCoefForward: 0.5
KI_P_qw: 0
KD_4: 0.24
footDistance: 0.163
footApexPhase: 0.5
KP_P_qw: 0
trunkYOnlyInDoubleSupport: false
KD_2: 0