Angle:
  amount: 5
  bottom1_1: -50
  upper1_1: -45
  upper2_1: -25
  bottom2_1: -20
  bottom1_2: -25
  upper1_2: -20
  upper2_2: -16
  bottom2_2: -13 
  bottom1_3: -16
  upper1_3: -13
  upper2_3: 13
  bottom2_3: 16
  bottom1_4: 13
  upper1_4: 16
  upper2_4: 20
  bottom2_4: 25
  bottom1_5: 20
  upper1_5: 25
  upper2_5: 45
  bottom2_5: 50
  bottom1_6: 13
  upper1_6: 16
  upper2_6: 18
  bottom2_6: 20
  bottom1_7: 18
  upper1_7: 20
  upper2_7: 45
  bottom2_7: 50
Gyro:
  amount: 3
  bottom1_1: -3
  upper1_1: -1
  upper2_1: -0.7
  bottom2_1: -0.5
  bottom1_2: -0.7
  upper1_2: -0.5
  upper2_2: 0.5
  bottom2_2: 0.7
  bottom1_3: 0.5
  upper1_3: 0.7
  upper2_3: 1
  bottom2_3: 3
Kp:
  amount: 3
  bottom1_1: 1.5
  upper1_1: 3.60
  upper2_1: 3.60
  bottom2_1: 4.20
  bottom1_2: 3.60
  upper1_2: 4.20
  upper2_2: 4.20
  bottom2_2: 5.00
  bottom1_3: 4.20
  upper1_3: 5.00
  upper2_3: 5.00
  bottom2_3: 6.00
  bottom1_4: 7.50
  upper1_4: 9.50
  upper2_4: 9.50
  bottom2_4: 12.00
  bottom1_5: 9.50
  upper1_5: 12.00
  upper2_5: 12.00
  bottom2_5: 20.00
Kd:
  amount: 3
  bottom1_1: 0.5
  upper1_1: 0.8
  upper2_1: 0.8
  bottom2_1: 1.1
  bottom1_2: 0.8
  upper1_2: 1.1
  upper2_2: 1.1
  bottom2_2: 1.4
  bottom1_3: 1.1
  upper1_3: 1.4
  upper2_3: 1.4
  bottom2_3: 1.7
CapturePoint:
  CP_active: false
  CP_GAIN: -10 #-5